# Generated by Django 6.0.7 on 2026-08-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='篇名')),
                ('description', models.TextField(blank=True, verbose_name='篇目说明')),
            ],
        ),
        migrations.AddField(
            model_name='sliptext',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slip_texts', to='texts.chapter', verbose_name='篇目'),
        ),
    ]
