# Generated by Django 6.0.7 on 2026-08-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_chapter_sliptext_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliptext',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='slip_order',
            field=models.JSONField(blank=True, default=list, help_text="按顺序存储该篇所有简，如 ['41', '1', '37A', '2']", verbose_name='简序'),
        ),
    ]
