# Generated by Django 6.0.7 on 2026-08-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_remove_sliptext_chapter_chapter_slip_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliptext',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slip_texts', to='texts.chapter', verbose_name='篇目'),
        ),
        migrations.AddField(
            model_name='sliptext',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='简序'),
        ),
    ]
