# Generated by Django 6.0.7 on 2026-08-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_sliptext_chapter_sliptext_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliptext',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='sliptext',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slip_texts', to='texts.chapter', verbose_name='篇目'),
        ),
    ]
