# Generated by Django 6.0.7 on 2026-08-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_rename_content_sliptext_text_alter_sliptext_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliptext',
            old_name='text',
            new_name='content',
        ),
    ]
