# Generated by Django 6.0.7 on 2026-08-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_rename_text_sliptext_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliptext',
            name='parallel_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='对读'),
        ),
        migrations.AddField(
            model_name='sliptext',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='出处'),
        ),
    ]
