# Generated by Django 6.0.7 on 2026-08-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0007_sliptext_parallel_text_sliptext_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=50, verbose_name='评论者')),
                ('content', models.TextField(verbose_name='内容')),
                ('comment_type', models.CharField(choices=[('lidng', '隶定/释读'), ('yinyun', '音韵'), ('guwenzi', '古文字'), ('cili', '辞例'), ('zonghe', '综合'), ('other', '其他')], default='lidng', max_length=20, verbose_name='类型')),
                ('reliability', models.PositiveSmallIntegerField(default=0, verbose_name='可靠度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='texts.sliptext', verbose_name='竹简')),
            ],
            options={
                'verbose_name': '集释评论',
                'verbose_name_plural': '集释评论',
                'ordering': ['created_at'],
            },
        ),
    ]
