# Generated by Django 6.0.7 on 2026-08-06 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliptext',
            options={'ordering': ['chapter', 'order', 'slip_id']},
        ),
        migrations.AlterField(
            model_name='sliptext',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slip_texts', to='texts.chapter', verbose_name='篇目'),
        ),
    ]
