# Generated by Django 6.0.7 on 2026-08-06 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0009_alter_sliptext_options_alter_sliptext_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliptext',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('lishi', '隶定意见'), ('shiyi', '释义意见'), ('yinyun', '音韵证据'), ('cixian', '古文献辞例'), ('bianlian', '编联意见'), ('zonghe', '综合意见'), ('qita', '其他')], max_length=20, verbose_name='集释类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='集释内容')),
                ('evidence', models.TextField(blank=True, help_text='所引用的音韵、古文字、辞例等证据', verbose_name='证据引用')),
                ('author', models.CharField(max_length=100, verbose_name='评论人')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('confidence', models.IntegerField(default=0, help_text='1-5，数值越高越可靠', verbose_name='可靠度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='texts.sliptext', verbose_name='所属竹简')),
            ],
            options={
                'verbose_name': '集释',
                'verbose_name_plural': '集释',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
