# Generated by Django 6.0.7 on 2026-08-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0010_alter_sliptext_options_annotation_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glyph', models.CharField(max_length=10, unique=True, verbose_name='释读')),
                ('initial', models.CharField(blank=True, max_length=20, verbose_name='声母')),
                ('rhyme', models.CharField(blank=True, max_length=20, verbose_name='韵部')),
                ('pronunciation', models.CharField(blank=True, max_length=10, verbose_name='读音')),
                ('glyph_image', models.ImageField(blank=True, null=True, upload_to='glyphs/', verbose_name='字形图片')),
                ('ligature_code', models.CharField(blank=True, max_length=100, verbose_name='构字式')),
                ('meaning', models.TextField(blank=True, verbose_name='释义')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SlipChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='在竹简上的位置')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.character', verbose_name='字')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slipchars', to='texts.sliptext', verbose_name='所属竹简')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
