# Generated by Django 6.0.7 on 2026-08-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_character_slipchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliptext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slips/', verbose_name='图版'),
        ),
        migrations.AlterField(
            model_name='slipchar',
            name='position',
            field=models.IntegerField(default=0, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='slipchar',
            name='slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slipchars', to='texts.sliptext', verbose_name='竹简'),
        ),
    ]
