# Generated by Django 6.0.7 on 2026-08-08 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0012_sliptext_image_alter_slipchar_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glyph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='glyphs/%Y/%m/', verbose_name='字形图片')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='在简上的位置')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='图片来源')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glyphs', to='texts.character', verbose_name='所属字')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glyphs', to='texts.sliptext', verbose_name='所在竹简')),
            ],
            options={
                'verbose_name': '字形',
                'verbose_name_plural': '字形',
                'ordering': ['slip', 'position'],
                'unique_together': {('character', 'slip', 'position')},
            },
        ),
    ]
