# Generated by Django 6.0.7 on 2026-08-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0013_glyph'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlyphAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('lishi', '隶定意见'), ('shiyi', '释读意见'), ('xiesheng', '谐声域意见'), ('zonghe', '综合意见'), ('qita', '其他')], max_length=20, verbose_name='类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('reading', models.CharField(blank=True, max_length=20, verbose_name='释读')),
                ('content', models.TextField(verbose_name='集释内容')),
                ('evidence', models.TextField(blank=True, help_text='所引用的音韵、古文字、辞例等证据', verbose_name='证据引用')),
                ('author', models.CharField(max_length=100, verbose_name='评论人')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('confidence', models.IntegerField(default=0, help_text='1-5', verbose_name='可靠度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('glyph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='texts.glyph', verbose_name='字形')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
