# Generated by Django 6.0.7 on 2026-08-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0014_glyphannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='评论人')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='texts.chapter', verbose_name='所属篇章')),
            ],
            options={
                'verbose_name': '篇章评论',
                'verbose_name_plural': '篇章评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
