# Generated by Django 6.0.7 on 2026-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0015_chaptercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'ordering': ['order', 'name'],
            },
        ),
    ]
