# Generated by Django 6.0.7 on 2026-08-11 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0016_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='texts.collection', verbose_name='所属批次'),
        ),
    ]
