# Generated by Django 6.0.7 on 2026-08-11 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0017_chapter_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['title'], 'verbose_name': '篇目', 'verbose_name_plural': '篇目'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['glyph'], 'verbose_name': '字', 'verbose_name_plural': '字'},
        ),
        migrations.AlterModelOptions(
            name='sliptext',
            options={'ordering': ['order'], 'verbose_name': '竹简释文', 'verbose_name_plural': '竹简释文'},
        ),
        migrations.CreateModel(
            name='CollectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='评论人')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_approved', models.BooleanField(default=False, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='texts.collection', verbose_name='批次')),
            ],
            options={
                'verbose_name': '批次评论',
                'verbose_name_plural': '批次评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
