# Generated by Django 6.0.7 on 2026-08-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0018_alter_chapter_options_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipchar',
            name='status',
            field=models.CharField(blank=True, default='', help_text="多个状态用逗号分隔，如 '残损,重文'", max_length=50, verbose_name='字状态'),
        ),
    ]
