# Generated by Django 6.0.7 on 2026-08-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0019_slipchar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pronunciation_ascii',
            field=models.CharField(blank=True, max_length=100, verbose_name='拼音'),
        ),
    ]
